# Generated by Django 6.0.5 on 2026-05-24 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('car', 'Car')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity_units', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-created_at'],
            },
        ),
    ]
